---
job_type: "train"
organ: "Liver"  # Spleen, KidneyR, Pancreas
view: "View_1"  # View_1, Both, View_2
use_wandb: False  # True if you want to use weights and biases

data:
  # ovdje podrazumjevamo da ce slike biti u direktoriju Images, a maske
  # u direktoriju Masks{organ}. Nisam zicer je li to ok, ali je svakako urednije
  paths:
    #- "./data/abd/"
    - "./data/rch/"
  train_validation_test_split_ratio:
    # - [seed, train, validation, test]
    #- [0, 1.0, 0.0, 0.0]
    - [0, 0.4, 0.3, 0.3]
    #- [0, 0.3, 0.4, 0.3]
    #- [0, 0.3, 0.4, 0.3]
  dirty_data:
    remove_dirty_data: False
    paths:
      #- ['./dirty_data/abd_corr_view_white_80.csv', './dirty_data/abd_corr_view_foggy_95.csv']
      #- ['./dirty_data/rk_corr_view_white_90.csv', './dirty_data/rk_corr_view_foggy_95.csv']
      #- ['./dirty_data/abd_artefacts_white_80.csv', './dirty_data/abd_artefacts_foggy_95.csv']
      #- ['./dirty_data/rk_artefacts_white_90.csv', './dirty_data/rk_artefacts_foggy_95.csv']
  images_per_patient: 300
  augmentation: False

backbone:  # za buducnost kada cemo imati istreniran backbone
  name: null
  backbone_path: null

organ_merging:
  using_organ_merging: False
  number_of_merged_organs: 1

save_paths:
  time_and_date_format: "%d-%m-%Y__%H-%M-%S"
  model: "./models/"
  patients: "./patients_distribution/"
  save_weights: False

segmentation_model:
  compile: True
  batch_size: 64
  epochs: 2
  backbone: "efficientnetb0"
  loss: "Jaccard"
  activation: "sigmoid"
  number_of_classes: 1
  encoder_weights: "imagenet"
  encoder_freeze: True
  checkpoint_path: "./tensorflow_models/"
  scheduler:
    exponential:
      using: True
      initial_learning_rate: 0.001
      decay_steps: 50
      decay_rate: 0.9
    cosine:
      using: False
      initial_learning_rate: 0.001
      first_decay_steps: 40
      t_mul: 1.2
      m_mul: 1.0
      alpha: 0
  callbacks:
    early_stopping:
      early_stopping_monitor: "val_loss"
      early_stopping_mode: "auto"
      early_stopping_patience: 15
      early_stopping_restore_best: False
      early_stopping_min_delta: 0
      early_stopping_baseline: null
